### ISSUE TITLE
I need help with transformer's output, attns.

### ISSUE THREAD

**Issue by eenzeenee** [zarzouram/image_captioning_with_transformers#1]
Hello. I am so grateful that you wrote this implementation code.

I want to use this code to learn the model with the coco dataset, but I have a problem, so I leave a question.
While using the "run_train.py" code, an error such as a photo occurred.

![스크린샷 2022-09-16 오후 9 00 49](https://user-images.githubusercontent.com/71638597/190635176-3d888a85-4707-424d-9e5b-c0e33d5c3940.png)

At this time, attns should look like [layer_num, head_num, batch_size, max_len, code_size^2], but in my result, it appears that the dimension corresponding to [layer_num, batch_size, max_len, code_size^2] has disappeared.

To solve this problem, efforts were made to look at "models/IC_encoder_decoder/transformer.py", which seems to be a problem that occurs when attns is created through a module called layer. I'm leaving a question because I was wondering if there was a way to solve this problem.

I'll be waiting for your reply.

+ In addition, due to lack of English skills, the tone of the question may be unpleasant. I ask for your generous understanding of this.

**Comment by eenzeenee** [comment]
It is understood as a problem caused by missing your "IMPORTANT NOTE". 
Thanks to the detailed explanation, it could be solved. 
Thank you.

**Comment by zarzouram** [comment]
Hello,

I have just seen your question. I am glad you figured it out. Thank you for the update.

Another solution could be using a newer version of PyTorch. The newer version provides the attention weights per transformer head. Please see PyTorch document for the MultiheadAttention [here](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html). 

Line 89 in [models/IC_encoder_decoder/decoder_layers.py](https://github.com/zarzouram/image_captioning_with_transformers/blob/623a8d31418db720acfe5e650dfd000c88ada988/code/models/IC_encoder_decoder/decoder_layers.py#L89) would be:
```python
output2, attns = self.multihead_attn(output, enc_outputs, enc_outputs, need_weights=True, average_attn_weights=False)
```

However, I am not sure whether using a newer version of PyTorch could cause other dependencies issues.

**Comment by eenzeenee** [comment]
Oh, there's also the effect of the Pytorch version! 
Thank you for the additional information!
