### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by stanthemaker** [zarzouram/image_captioning_with_transformers#2]
Hi, I was trying to inference some captions, and I encountered bug shown below.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/79928691/202391650-964b7394-5b6a-4dab-a916-539efce70cec.png">

- As shown above, there are some captions generated, thus my code is able to inference some captions.
- For the checkpoint I wished to inference, it always broke when inferencing 16th image.
- Precisely, the source code locates at line 228 at [image_captioning_with_transformers](https://github.com/zarzouram/image_captioning_with_transformers)/[code](https://github.com/zarzouram/image_captioning_with_transformers/tree/main/code)/inference_test.py

By the way, thanks a lot for your repo.

**Comment by stanthemaker** [comment]
A quick update, I found out it was caused by predicted caption being too long.
Probably because I didn't trained my model well enough, but still, is there any way to prevent this from happening when inferencing?
<img width="746" alt="image" src="https://user-images.githubusercontent.com/79928691/202396496-f954f1d5-4633-4065-b1eb-907afef16dc0.png">

**Comment by zarzouram** [comment]
Hi,

Thank you for your messages. You seem to have `seq_preds, seq_attns, seq_log_probs` as empty lists. These lists are formed as soon as the `EOS` token is generated. See line 212 `if torch.any(seqs_end):` So, I think your conclusion is correct. The generated captions aretoo long, and the EOS is never generated.

To solve this issue, you may get predictions and attention from `current_preds` and `attns` tensors and sort them based on the `log_prob_topk` tensor if `seq_preds` is empty.

Thank you for pointing this out. I did not face this issue, but I think the code logic should take care of such a condition.

**Comment by felipezeiser** [comment]
Hi, 

I know it's a bit late, but how did you solve that @stanthemaker ?

Thank you.
