### ISSUE TITLE
Confusion about "vector_dir" when preparing dataset

### ISSUE THREAD

**Issue by FerryHuang** [zarzouram/image_captioning_with_transformers#3]
Thanks for your great work! I'm trying to reproduce your results but stucked on running the `create_dataset.py`. I have read through the instructions on preparing datasets but got confused about set the "vector_dir" as Directory to the pre-trained embedding vectors files. Where can I get the files or zips. Have I missed some important part of the instructions?

**Comment by zarzouram** [comment]
I'm sorry for not getting back to you sooner.

`vector_dir` is `vectors_cache` that is used by `torchtext.vocab.Vocab` initializer; see torchtext document here: https://text-docs.readthedocs.io/en/latest/vocab.html#vocab

If you are going to use Glove, download Glove files from the Glove vectors website; the `vector_dir` is the directory that contains the downloaded files.
